
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.Console;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Hangman testHangman = new Hangman();
        Scanner myConsole = new Scanner(System.in);

    }
}
