
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HangmanTest {

    // @Test public void selectWord_returnsWordFromMyWords_true() {
    //     Hangman testHangman = new Hangman();
    //     String expected = "hello";
    //     assertEquals(expected, testHangman.selectWord("hello");
    // }
}
